---
- name: configure VLANs 
  hosts: cisco
  gather_facts: false
  tasks: 
    - name: VLANs task
      cisco.nxos.vlans:
        config:
        - vlan_id: 5
          name: WEB
        - vlan_id: 10

