---
- hosts: cisco

  vars:
    vlan_name: users
    vlan_id: 20

  tasks:
    - name: Create VLAN
      cisco.ios.ios_vlans:
        config:
        - name: "{{ vlan_name }}"
          vlan_id: "{{ vlan_id }}"
          state: active
